ci: clang-format cannot produce the right return value (#29)
Signed-off-by: taofengliu <liutaofeng.ltf@antgroup.com>
(cherry picked from commit c26056990d64f2cd8b98da2d9082c749d0bab105)

diff --git a/.github/workflows/jeandle-llvm-test.yml b/.github/workflows/jeandle-llvm-test.yml
--- a/.github/workflows/jeandle-llvm-test.yml
+++ b/.github/workflows/jeandle-llvm-test.yml
@@ -56,3 +56,9 @@ jobs:
           git fetch --depth=1 jeandle-main
           sudo apt-get install -y clang-format
           git clang-format jeandle-main/main
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Format check failed!"
+            exit 1
+          else
+            exit 0
+          fi
